### PR TITLE
Fix config to work with Android NDK r19

### PR DESCRIPTION
**Pull request by rafleon**

### CODE REVIEW

**Comment by mgorges** [comment]
Great suggestion - I am wondering if the "-fPIC" would be better placed in the `targets/android/host_macosx' file, as that way it would also be applied when building libraries? (I initially had problems with an app that used OpenSSL, but changing this seems to work?

> SYS_CC=$android_cross"gcc $SYS_DEBUGFLAG -fPIC -DANDROID -D__ANDROID_API__=${ANDROIDAPI} -isysroot $android_sysroot $cflag_additions"

**Comment by mgorges** [comment]
Also why did you remove the support library moving piece which looks in `$ANDROIDSDK/extras/android/m2repository/com/android/support [...]` and still seems to be a moving target?

**Comment by rafleon** [comment]
Adding -fPIC to the SYS_CC command would be a more general change, and I wasn't sure if it would cause a noticeable performance penalty. Using -fPIC would definitely improve compatibility, and I bet nobody would notice the performance difference.

**Comment by mgorges** [comment]
Good point, however the change to `payload_cdefs` is not sufficient as the libraries also need it (or at least OpenSSL needed it).

**Comment by rafleon** [comment]
With the extra support library included, I get this error using the latest version of Android Studio and build tools:

-dex:
      [dex] input: /home/paco/.lambdanative/tmp_build/bin/classes
      [dex] input: /home/paco/.lambdanative/tmp_build/libs/support-v4-19.1.0.jar
      [dex] input: /home/paco/.lambdanative/tmp_build/libs/android-support-v4.jar
      [dex] Pre-Dexing /home/paco/.lambdanative/tmp_build/libs/support-v4-19.1.0.jar -> support-v4-19.1.0-c13131761f8e5a08474928926bcb545b.jar
      [dex] Pre-Dexing /home/paco/.lambdanative/tmp_build/libs/android-support-v4.jar -> android-support-v4-73c33b7bd7fab1b261aae76d0abe8b4b.jar
      [dex] Converting compiled files and external libraries into /home/paco/.lambdanative/tmp_build/bin/classes.dex...
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:660)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:615)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:597)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:197)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:503)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:333)
       [dx] 	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:244)
       [dx] 	at com.android.dx.command.Main.main(Main.java:95)
       [dx] 
BUILD FAILED
/home/paco/android/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/paco/android/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/paco/android/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/paco/android/tools/ant/build.xml:283: null returned: 2
Total time: 13 seconds
ERROR: failed with exit code 1
BUILD FAILED - configure with verbose option for more information
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

By removing it, this error disappears.

**Comment by mgorges** [comment]
The `support-v4-19.1.0.jar` might be the wrong version to match your SDK target level - we might need to automatically identify the right one to include

**Comment by rafleon** [comment]
ANDROIDAPI=19 in SETUP.  Something else is going on. I will need to research this more.

**Comment by mgorges** [comment]
Thanks for the updated patch. If you can find out about the `Multiple dex files define` problem, do let us know, otherwise I'll merge later this evening. I am now using SDK level 26, which is the minimum Google Play Store level.

**Comment by rafleon** [comment]
I tried ANDROIDAPI=28 and see the same error.  [This stackoverflow answer](https://stackoverflow.com/a/23391996) is the one that I followed and suggests removing the support-v4 from the libs folder.

**Comment by mgorges** [comment]
Alright, lets remove it unless it causes other problems. Thanks for the pull request, much appreciated!

**Pull request merged**
