### PR TITLE
GLGUI: fix chat widget update.

### PR DESCRIPTION
**Pull request by 0-8-15**
Until now the chat widget caches a pre-processed version of the
list of entries to display keyed on the `length` of the list.

Avoiding some exponential complexity during drawing, there was and
upper bound of the length maintained.  This broke once the list grew
beyond that.

This change slightly modifies the cache - and therefore renames it
within the widget.

The new caching tests ONLY whether or not the old list is the SAME in
terms of `eq?` as the new one.  It INTENSIONALY does NOT try to detect
updates to the components of the list.  This decision was made because
drawing happens much, much more frequent than updates.  It is trivial
on the update side to avoid side effects, but costly on the drawing
side to detect them.

### CODE REVIEW

**Comment by mgorges** [comment]
If one makes the reasonable assumption that for `glgui-chat` new items are typically appended at the end/bottom, instead of changing items within it, the lack of test of internal changes is probably okay. However, this wouldn't generalize for the regular `glgui-list`, which this is a special case of. Thus, I am wondering if we should provide a `glgui-chat-[updatelist]` type function that ensures both update cases: append and replacement are supported? Also, it might be useful to have a one-item comment in the constructor that points out that unlike `glgui-list`, this one cannot be simply modified by updating the `'list` list, if the length doesn't also change?

**Comment by 0-8-15** [comment]
Am Tue, 06 Oct 2020 15:29:37 -0700
schrieb Matthias Görges <notifications@github.com>:

> If one makes the reasonable assumption that for `glgui-chat` new
> items are typically appended at the end/bottom, instead of changing
> items within it, the lack of test of internal changes is probably
> okay. However, this wouldn't generalize for the regular `glgui-list`,
> which this is a special case of. Thus, I am wondering if we should
> provide a `glgui-chat-[updatelist]` type function that ensures both
> update cases: append and replacement are supported? Also, it might be
> useful to have a one-item comment in the constructor that points out
> that unlike `glgui-list`, this one cannot be simply modified by
> updating the `'list` list, if the length doesn't also change?

IMHO the assumption that the length has to change is the bad idea.

I'm re-using the chat widget to switch from one channel to another.  If
there are the same amount of messages in both chats I'm lost already.
Same goes for "keep it usable by allowing the option max a maximum
length".

The patch I made does allow both, append and update by imply updating
the 'list property.

I'd strongly recommend to NOT support a destructive update of the
list.  Reasons: a) performance, checking this case is expensive
while declaring the list immutable is simple b) error prone to implement
correctly c) I don't see it used in a destructive update case anywhere
and d) doing so would be bad practice and trivially fixed.

**Comment by mgorges** [comment]
I guess I didn't quite understand the final paragraph of your initial submission correctly? It read like a warning that the new approach does NOT detect changes to internal elements within the list? Will try this out tomorrow and then merge if it handles all updates as expected by simply setting the `'list` to a new value.

**Comment by 0-8-15** [comment]
Am Wed, 07 Oct 2020 01:39:28 -0700
schrieb Matthias Görges <notifications@github.com>:

> I guess I didn't quite understand the final paragraph of your initial
> submission correctly? It read like a warning that the new approach
> does NOT detect changes to internal elements within the list? Will
> try this out tomorrow and then merge if it handles all updates as
> expected by simply setting the `'list` to a new value.

That one should be working.

Destructive updates, which keep the first pair fixed and use set-cdr!
to extend the list are not detected.

**Comment by 0-8-15** [comment]
Am Wed, 07 Oct 2020 01:39:28 -0700
schrieb Matthias Görges <notifications@github.com>:

> I guess I didn't quite understand the final paragraph of your initial
> submission correctly? It read like a warning that the new approach
> does NOT detect changes to internal elements within the list? Will
> try this out tomorrow and then merge if it handles all updates as
> expected by simply setting the `'list` to a new value.

Looks like having fixed the androidforegroundservice to work again has
dealt with the issue.

**Comment by mgorges** [comment]
> Looks like having fixed the androidforegroundservice to work again has dealt with the issue.

Not quite sure what this refers to here?

**Comment by 0-8-15** [comment]
> > Looks like having fixed the androidforegroundservice to work again has dealt with the issue.

Wrong thead, belongs to #339.

**Pull request merged**
