### PR TITLE
enable C profiling and debugging of Scheme code.

### PR DESCRIPTION
**Pull request by 0-8-15**
This might be helpful to track the breakage under mac down.

Also likely helpful to reveal bottlenecks by profiling.

### CODE REVIEW

**Comment by mgorges** [comment]
That sounds like a wonderful addition. Would you mind adding a paragraph to https://github.com/part-cw/lambdanative/wiki/Debugging about how you use `gprof` on Linux, as it doesn't run on macOS, where one has to use Google's `pprof` or another solution instead?

**Comment by 0-8-15** [comment]
Done.

Am Sat, 10 Oct 2020 16:19:01 -0700
schrieb Matthias Görges <notifications@github.com>:

> That sounds like a wonderful addition. Would you mind adding a
> paragraph to https://github.com/part-cw/lambdanative/wiki/Debugging
> about how you use `gprof` on Linux, as it doesn't run on macOS, where
> one has to use Google's `pprof` or another solution instead?

**Comment by mgorges** [comment]
Thanks.

**Comment by 0-8-15** [comment]
Am Sat, 10 Oct 2020 16:19:01 -0700
schrieb Matthias Görges <notifications@github.com>:

> That sounds like a wonderful addition. Would you mind adding a
> paragraph to https://github.com/part-cw/lambdanative/wiki/Debugging

That page details how to debugging unused variables:
https://github.com/part-cw/lambdanative/wiki/Debugging#undefined-variable-example-using-debug-mode

That's been a major issue for me all the time (being slightly visually
impaired it happens to me all the time).  I tried this out, but no
effect.  Does this work for you?

**Comment by mgorges** [comment]
> That's been a major issue for me all the time (being slightly visually impaired it happens to me all the time). I tried this out, but no effect. Does this work for you?

On Linux with **libgambc** it does - see Gist: https://gist.github.com/mgorges/9727d3eb702a408b559c0c8eac8295c4

**Comment by mgorges** [comment]
On MacOS with **libgambit** it does NOT, and makes one of those wonderful primordial loop things - see Gist: https://gist.github.com/mgorges/320fd2bd2ea7b98cf4283028a82aeed3

**Pull request merged**
