### PR TITLE
ANDROID: JNI error checking and free local references

### PR DESCRIPTION
**Pull request by 0-8-15**
there will be more in audio at least, not yet written.

### CODE REVIEW

**Comment by mgorges** [comment]
Sorry, I don't see anything with respect to error checking - only freeing of three references? Did you mean to include something else in this pull request as well?

**Comment by 0-8-15** [comment]
Am Wed, 02 Dec 2020 18:33:22 -0800
schrieb Matthias Görges <notifications@github.com>:

> Sorry, I don't see anything with respect to error checking - only
> freeing of three references? Did you mean to include something else
> in this pull request as well?

Java error checking in this case, here: `JNI_forward_exception_to_gambit`

**Comment by mgorges** [comment]
But that was there before the commit already?

**Comment by 0-8-15** [comment]
Maybe, in which case it is just plugging a memory leak.

https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/jni_refs.html#d8649e76

**Pull request merged**
