### PR TITLE
define cond expand feature debug

### PR DESCRIPTION
**Pull request by 0-8-15**
This enables compile-time instrumentation/alteration of code depending
on the configured options.

### CODE REVIEW

**Comment by mgorges** [comment]
Happy to merge this after I tested, but I am wondering if we need to start having more than one debug level as it seems we are creeping towards so much extra stuff that things are getting long to compile and run that somewhat limits the ability to use debug mode in everyday development?

**Comment by 0-8-15** [comment]
Am Fri, 20 Nov 2020 10:10:19 -0800
schrieb Matthias Görges <notifications@github.com>:

> Happy to merge this after I tested, but I am wondering if we need to
> start having more than one debug level as it seems we are creeping
> towards so much extra stuff that things are getting long to compile
> and run that somewhat limits the ability to use debug mode in
> everyday development?

;-)

+1

My first commit message included a paragraph with the same idea.

Just how this could be done in an extensible and easy to customize way
it currently beyond me.

**Comment by mgorges** [comment]
Is this case sensitive? - The only place I find when I search for this on Google is https://mailman.iro.umontreal.ca/pipermail/gambit-list/2007-May/001368.html which uses `DEBUG` which is also what we use in C?

**Comment by 0-8-15** [comment]
Am Sat, 21 Nov 2020 21:09:36 -0800
schrieb Matthias Görges <notifications@github.com>:

> Is this case sensitive? - The only place I find when I search for
> this on Google is
> https://mailman.iro.umontreal.ca/pipermail/gambit-list/2007-May/001368.html
> which uses `DEBUG` which is also what we use in C?

Judging from the current code base I would be surprised if we started
suddenly to favor uppercase for Scheme identifier.

With Gambit one can control via the reader settings whether or not
source code is case sensitive.  By default it is.  (Though the original
default for Scheme was not to be.)

Personally I tend to prefer case sensitive symbols and typically write
them in lower case.

Eventually: maybe we can please either take it as is or leave it out
completely.  I'm actually using the lower case version everywhere and I
will not go back and change all the code.

**Comment by mgorges** [comment]
Alright I will refer people to this when the complaints about this being inconsistent start coming in.

**Pull request merged**
