### PR TITLE
Support macro loading per file.

### PR DESCRIPTION
**Pull request by 0-8-15**
This patch provides a partial way to specify compile time macros.

Iff there is a file with the same basename and an extension .sch
the latter is loaded into gambit via -e option.

Caveat:

lambdanative does not check the .sch file for modifications like it
does with the .scm files.  Updates to the file do not trigger a
recompile.

A real solution would be to support r7rs style library declarations.

### CODE REVIEW

**Comment by mgorges** [comment]
I am confused by this comment: `lambdanative does not check the .sch file for modifications like it does with the .scm files.  Updates to the file do not trigger a recompile.`, as it seems you do check for that time and trigger a recompile?

**Comment by 0-8-15** [comment]
I found that languages/scm.sh uses `newersourceindir` to check all
*.scm files in the directory of the $scm_src given.  Now that I'm
adding the *.sch file this is not being checked the same way.

Maybe that should be done.

I still wonder, maybe tehre is a better way to accomplish the trick.
Just beyond me.

Am Thu, 23 May 2019 13:31:00 -0700
schrieb Matthias Görges <notifications@github.com>:

> I am confused by this comment: `lambdanative does not check the .sch
> file for modifications like it does with the .scm files.  Updates to
> the file do not trigger a recompile.`, as it seems you do check for
> that time and trigger a recompile?
>

**Comment by mgorges** [comment]
The [newersourceindir](https://github.com/part-cw/lambdanative/blob/master/make.sh#L180) test only works for *.scm, as that is the only language that is currently defined in this repository. However, the testing loop could be used instead of line 107 of the patch to get higher coverage of all *.sch files?

**Comment by 0-8-15** [comment]
I'm slightly confused which line 107 you referred to.

At the other hand I'm not convinced that the approach to recompile a `.scm` file whenever another `.scm` file in the same directory has changed is a good one in the first place.

The real solution(TM) is IMHO to use r7rs library definitions to resolve dependencies.  That could handle syntax definitions imported from other modules/locations, normal code, larger modules with code in subdirectories etc.  Currently I to have a a look into how this could be done. [black hole](https://github.com/per-gron/blackhole) and [SchemeSpheres](http://www.schemespheres.org/) came up as options.

For the time being, I'd rather not add more complexity to the build process.  The proposed change would support precisely one `.sch` file of the same `basename` as the file to be compiled.

**Comment by mgorges** [comment]
I was referring to that line in your [pull request diff](https://github.com/part-cw/lambdanative/pull/240/commits/cbb9d1eecfebd52886b27706c7ce2368abf25844#diff-22273f1d94f654e2c8e76c51bc402760R107), which is 
> if [ -f $scm_hdr -a `isnewer "$scm_hdr" "$scm_otgt"` = "yes" ]; then`

However, given that you don't wish to expand it to allow wildcard support, I'll review the pull request as is and merge if it doesn't cause obvious issues.

**Pull request merged**
