### PR TITLE
Ln_repl define global macros

### PR DESCRIPTION
**Pull request by fungiblecog**
Another enhancement as per issue #117. This one makes all the globally defined macros (in global-macros.scm files) available at the repl when you connect. It's a bit more involved than the previous change as I changed the make.sh script to create a file *all-global-macros*.scm in the ln_repl module directory. This has all the global macro definitions stashed away so they can be eval'd when a connection is made to the repl.

### CODE REVIEW

**Comment by mgorges** [comment]
@fungiblecog I'll reject and close this one and will ask you to redo the pull-request for two reasons:
a) 3/4 commits are already included in #119, so please rebase against master
b) your make.sh commit alters files in LN's modules/ln_repl folder. To allow system-wide installations, where the LamdbaNative folder is not user-writeable, this won't work for us. Shouldn't they already be included through the compilation anyway?

I'll discuss with @clpetersen on Monday how to accommodate this in a better way. Sorry Matthias

**Comment by fungiblecog** [comment]
a)  I haven't done a 'pull request' before and didn't realise that the second one would also include the first set of changes. Lesson learned there.

b) In order to make the macro definitions available at run-time (they vanish after compilation) I need to stash the contents of the global-macros.scm files in the cache away into a data structure. The only way I could find to do this was to change the make.sh script to create a file in the ln_repl folder. If you can think of a better way to do this I'd love to hear it. In common lisp 'eval-when' allows code run at compile time to set up this kind of thing, but I don't think scheme has this? Even with 'eval-when' I don't think code running in the module would be able to access a file direct from the cache?

**Comment by mgorges** [comment]
@fungiblecog no problem about a, we all start somewhere. As for b, I'll see if I can get them into the cache somehow automatically, so they are evaluated at runtime. I don't know about `eval-when` but it is mentioned in the gambit source `gambit/lib/syntax-case-prelude.scm`. Will look into it tomorrow.

**Comment by fungiblecog** [comment]
Thanks I'll have a look at that reference as well.

**Pull request closed without merging**
